#!/usr/bin/env bash
# ============================================================
# KEJA HALISI — STEP 2/3: Connect Supabase (Postgres + keys)
# ============================================================
# Usage (interactive — it will ask for the values):
#   bash scripts/deploy/02-supabase-env.sh
#
# Where to get each value (Supabase dashboard):
#   • Project ref / URL / anon key / service_role key → Settings → API
#   • Pooled + direct Postgres URLs                   → Connect (top bar)
#       - "Connection pooler"  (port 6543, pgbouncer) → DATABASE_URL
#       - "Direct connection"  (port 5432)            → DIRECT_URL  (insert your DB password)
#
# What it does (safe to re-run):
#   1. Collects + validates your Supabase values
#   2. Writes .env.production.local (gitignored — never committed)
#   3. Tests the REST endpoint with your anon key
#   4. Creates the tables (prisma db push on the Postgres schema) and seeds demo data
set -euo pipefail

BLUE='\033[1;34m'; GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
step() { echo -e "${BLUE}▶ $1${NC}"; }
ok()   { echo -e "${GREEN}✓ $1${NC}"; }
die()  { echo -e "${RED}✗ $1${NC}"; exit 1; }

ask() { # ask <var-name> <prompt> [default]
  local __var="$1" __prompt="$2" __default="${3:-}" __in=""
  if [ -n "${!__var:-}" ]; then __in="${!__var}"; else
    read -rp "$__prompt${__default:+ [$__default]}: " __in; [ -z "$__in" ] && __in="$__default"
  fi
  printf -v "$__var" '%s' "$__in"
}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Supabase → Keja Halisi production wiring"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

ask SUPA_URL      "Supabase Project URL (https://xxxx.supabase.co)"
[[ "$SUPA_URL" =~ ^https://[a-z0-9]{20}\.supabase\.co$ ]] || die "URL must look like https://abcdefghijklmnopqrst.supabase.co"

ask SUPA_ANON     "anon (publishable) key — Settings → API"
[ ${#SUPA_ANON} -lt 30 ] && die "anon key looks too short"

ask SUPA_SERVICE  "service_role key (SECRET — server only) — Settings → API"
[ ${#SUPA_SERVICE} -lt 30 ] && die "service_role key looks too short"

ask DB_POOLED     "Pooled Postgres URL (port 6543, includes :YOUR_DB_PASSWORD@)"
[[ "$DB_POOLED" =~ ^postgresql?:// ]] || die "DATABASE_URL must start with postgresql://"

ask DB_DIRECT     "Direct Postgres URL (port 5432, includes :YOUR_DB_PASSWORD@)" "$DB_POOLED"

ENV_FILE=".env.production.local"
step "Writing $ENV_FILE (gitignored)"
cat > "$ENV_FILE" <<EOF
# ── Generated by scripts/deploy/02-supabase-env.sh — DO NOT COMMIT ──
# Supabase
NEXT_PUBLIC_SUPABASE_URL=$SUPA_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SUPA_ANON
SUPABASE_SERVICE_ROLE_KEY=$SUPA_SERVICE

# Postgres (Prisma production schema: prisma/schema.postgres.prisma)
DATABASE_URL=$DB_POOLED
DIRECT_URL=$DB_DIRECT
EOF
grep -q '^\.env.production.local' .gitignore 2>/dev/null || echo ".env.production.local" >> .gitignore
ok "$ENV_FILE written (never committed)"

step "Testing Supabase REST endpoint with anon key"
HTTP=$(curl -s -o /dev/null -w "%{http_code}" "$SUPA_URL/rest/v1/?apikey=$SUPA_ANON" -H "apikey: $SUPA_ANON")
[ "$HTTP" = "200" ] || die "Supabase REST test failed (HTTP $HTTP) — check URL + anon key"
ok "Supabase reachable (HTTP 200)"

step "Creating tables via Prisma (prisma db push → schema.postgres.prisma)"
export DATABASE_URL="$DB_POOLED" DIRECT_URL="$DB_DIRECT"
bun run db:push:pg || die "prisma db push failed — check the pooled/direct URLs and DB password"

step "Seeding demo data (29 estates • 10 agents • 18 listings)"
bun run db:seed:pg || die "seed failed"

echo ""
ok "STEP 2 DONE → next: bash scripts/deploy/03-vercel-deploy.sh"
echo "  ⚠ Remember: Storage buckets (verification-docs, mandate-letters, listing-photos)"
echo "    must be created PRIVATE in Supabase → Storage (SQL + policies: supabase/migrations/0001_init.sql)."
