export const dynamic = "force-dynamic";
// GET /api/snapshots/[id] — serve a video-frame snapshot generated by the
// TikTok ingest agent. Listing rows never hold media bytes (link-only law);
// they hold /api/snapshots/<id> links that resolve here. The JPEG payload is
// stored base64 in the Snapshot table and served with immutable caching —
// snapshots are generated once and never mutate.
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

export async function GET(
  _req: NextRequest,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;
  const snap = await db.snapshot.findUnique({ where: { id } });
  if (!snap) {
    return new NextResponse("Snapshot not found", { status: 404 });
  }
  const bytes = Buffer.from(snap.dataBase64, "base64");
  return new NextResponse(new Uint8Array(bytes), {
    status: 200,
    headers: {
      "Content-Type": snap.mime || "image/jpeg",
      "Content-Length": String(bytes.length),
      // immutable: snapshot ids are unique per frame and content never changes
      "Cache-Control": "public, max-age=31536000, immutable",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
